Repository stackabletech/kafka-operator, pull requests merged in 2021-08, with the labels that each got.

#136 CLI handling for CRDs, dep updates, diagnostic startup information
  Cargo.lock
  crd/Cargo.toml
  crd/src/bin/generate_crds.rs
  deploy/crd/kafkacluster.crd.yaml
  operator/Cargo.toml
  operator/src/lib.rs
  server/Cargo.toml
  server/build.rs
  server/src/main.rs
Labels: type/enhancement, priority/medium

#142 Adapted to operator-rs build_resource_name and create_config_map
  Cargo.lock
  crd/src/lib.rs
  examples/simple-kafkacluster.yaml
  operator/src/error.rs
  operator/src/lib.rs
Labels: type/enhancement, priority/high

#143 Project updates
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/rust.yml
  CHANGELOG.md
  Cargo.lock
  crd/Cargo.toml
  deny.toml
  operator/Cargo.toml
  server/Cargo.toml
Labels: type/enhancement, priority/low
