Repository stackabletech/kafka-operator, pull requests merged in 2021-05, with the labels that each got.

#71 Removed label selector schema and switched to the one provided in ope…
  crd/src/lib.rs
Labels: priority/low, size/S

#74 Remove redundant release build and introduce caching
  .github/workflows/rust.yml
Labels: priority/low, size/XS, type/enhancement

#80 Added clean command to rust build.
  .github/workflows/rust.yml
Labels: type/enhancement

#92 Add Antora docs
  README.adoc
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/building.adoc
  docs/modules/ROOT/pages/dependencies.adoc
  docs/modules/ROOT/pages/index.adoc
  operator/src/lib.rs
Labels: priority/low, size/M, type/documentation

#96 ZooKeeper connect string is now retrieved via zookeeper get_zk_connec…
  Cargo.lock
  crd/Cargo.toml
  crd/kafkaclusters.crd.yaml
  crd/src/lib.rs
  examples/simple-kafkacluster.yaml
  operator/src/error.rs
  operator/src/lib.rs
Labels: priority/high, size/M, type/enhancement

#94 Added opa integration config parameters. Tested with kafka-2.13-2.8.0…
  Cargo.lock
  crd/Cargo.toml
  crd/kafkaclusters.crd.yaml
  crd/src/lib.rs
  examples/simple-kafkacluster.yaml
  operator/Cargo.toml
  operator/src/lib.rs
Labels: priority/high, size/S, type/enhancement

#102 Put the node_name in the ConfigMap
  operator/src/lib.rs
Labels: priority/critical, size/XS, type/bug

#101 Bring Kafka operator up to best practices
  .github/dependabot.yml
  .github/workflows/build_artifacts.yml
  .github/workflows/rust.yml
  Cargo.lock
  LICENSE
  crd/Cargo.toml
  crd/src/lib.rs
  crd/src/main.rs
  deploy/crd/kafkacluster.crd.yaml
  docs/modules/ROOT/pages/building.adoc
  operator/Cargo.toml
  server/Cargo.toml
  server/packaging/rpm/SPECS/stackable-kafka-operator-server.spec
  server/src/bin/generate_kafka_crd.rs
  server/src/main.rs
Labels: priority/low, type/enhancement

#109 Update handlebars version to 4.0
  Cargo.lock
  operator/Cargo.toml
Labels: type/bug
